import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { format, getDaysInMonth, startOfMonth } from 'date-fns'
import { Clock, LogIn, LogOut } from 'lucide-react'
import { attendanceApi } from '../../api/attendance'
import { getErrorMessage } from '../../api/client'
import { Badge, Button, Card, DataTable, EmptyState, Skeleton, type Column } from '../../components/ui'
import { useToast } from '../../components/ui/Toast'
import type { AttendanceRecord } from '../../types'
import { formatDate } from '../../lib/utils'

export function AttendancePage() {
  const month = format(new Date(), 'yyyy-MM'); const queryClient = useQueryClient(); const { toast } = useToast(); const query = useQuery({ queryKey: ['attendance', month], queryFn: () => attendanceApi.summary(month) })
  const action = useMutation({ mutationFn: (type: 'in' | 'out') => type === 'in' ? attendanceApi.checkIn() : attendanceApi.checkOut(), onSuccess: (_, type) => { queryClient.invalidateQueries({ queryKey: ['attendance'] }); toast(`Checked ${type} successfully`, 'success') }, onError: (error) => toast(getErrorMessage(error), 'error') })
  const columns: Column<AttendanceRecord>[] = [{ key: 'date', header: 'Date', render: (r) => <span className="font-mono">{formatDate(r.date)}</span> }, { key: 'employeeName', header: 'Employee' }, { key: 'checkIn', header: 'Check in', className: 'font-mono' }, { key: 'checkOut', header: 'Check out', className: 'font-mono' }, { key: 'workHours', header: 'Hours', render: (r) => <span className="font-mono">{r.workHours?.toFixed(1) ?? '—'}</span> }, { key: 'status', header: 'Status', render: (r) => <Badge variant={r.status}>{r.status.replace('_', ' ')}</Badge> }]
  if (query.isLoading) return <Skeleton className="h-[600px]" />
  if (!query.data) return <EmptyState title="Attendance unavailable" action={<Button onClick={() => query.refetch()}>Retry</Button>} />
  const now = new Date(); const days = getDaysInMonth(now); const firstOffset = startOfMonth(now).getDay(); const byDay = new Map(query.data.records.map((r) => [new Date(r.date).getDate(), r.status]))
  return <div><div className="mb-6"><p className="text-sm font-semibold uppercase tracking-wider text-accent">Time & presence</p><h1 className="text-3xl font-semibold">Attendance</h1><p className="mt-1 text-muted">Track working hours and monthly attendance.</p></div><div className="grid gap-6 xl:grid-cols-[1fr_1.5fr]"><Card className="flex flex-col justify-center bg-primary text-center text-white"><Clock className="mx-auto text-accent" size={34} /><p className="mt-4 text-sm text-white/60">{format(now, 'EEEE, dd MMMM')}</p><p className="mt-1 font-mono text-4xl font-semibold">{format(now, 'hh:mm a')}</p><p className="mt-3 text-sm">{query.data.checkedIn ? `Checked in at ${query.data.checkInTime}` : 'You have not checked in today'}</p><div className="mt-6 flex justify-center gap-3"><Button variant="secondary" onClick={() => action.mutate('in')} disabled={query.data.checkedIn}><LogIn size={17} />Check in</Button><Button className="bg-accent" onClick={() => action.mutate('out')} disabled={!query.data.checkedIn}><LogOut size={17} />Check out</Button></div></Card><Card><h2 className="text-xl font-semibold">{format(now, 'MMMM yyyy')}</h2><div className="mt-5 grid grid-cols-7 gap-2 text-center text-xs"><>{['S','M','T','W','T','F','S'].map((d, i) => <span key={`${d}${i}`} className="font-semibold text-muted">{d}</span>)}</>{Array.from({ length: firstOffset }).map((_, i) => <span key={`blank-${i}`} />)}{Array.from({ length: days }).map((_, i) => { const day = i + 1; const status = byDay.get(day); return <span key={day} title={status ?? 'No record'} className={`flex aspect-square items-center justify-center rounded-lg font-mono ${status === 'PRESENT' ? 'bg-emerald-500/20 text-emerald-700' : status === 'ABSENT' ? 'bg-red-500/15 text-red-700' : status === 'LATE' ? 'bg-amber-500/20 text-amber-700' : 'bg-background text-muted'}`}>{day}</span> })}</div></Card></div><Card className="mt-6"><h2 className="mb-5 text-xl font-semibold">Attendance logs</h2><DataTable data={query.data.records} columns={columns} getRowKey={(r) => r.id} /></Card></div>
}
