import { useQuery } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { Banknote, CircleDollarSign, Printer, ReceiptText } from 'lucide-react'
import { payrollApi } from '../../api/payroll'
import { Badge, Button, Card, DataTable, EmptyState, Skeleton, StatCard, type Column } from '../../components/ui'
import type { PayrollRecord } from '../../types'
import { formatCurrency } from '../../lib/utils'

export function PayrollPage() {
  const query = useQuery({ queryKey: ['payroll'], queryFn: () => payrollApi.list() })
  const columns: Column<PayrollRecord>[] = [{ key: 'employeeId', header: 'ID', className: 'font-mono' }, { key: 'employeeName', header: 'Employee' }, { key: 'month', header: 'Pay period', className: 'font-mono' }, { key: 'gross', header: 'Gross', render: (r) => <span className="font-mono">{formatCurrency(r.gross)}</span> }, { key: 'deductions', header: 'Deductions', render: (r) => <span className="font-mono">{formatCurrency(r.deductions)}</span> }, { key: 'net', header: 'Net pay', render: (r) => <span className="font-mono font-semibold">{formatCurrency(r.net)}</span> }, { key: 'status', header: 'Status', render: (r) => <Badge variant={r.status}>{r.status}</Badge> }, { key: 'actions', header: '', render: (r) => <Link to={`/payroll/${r.id}`} className="font-semibold text-primary hover:text-accent">Payslip</Link> }]
  if (query.isLoading) return <Skeleton className="h-[600px]" />
  if (!query.data) return <EmptyState title="Payroll data unavailable" action={<Button onClick={() => query.refetch()}>Retry</Button>} />
  return <div><div className="mb-6"><p className="text-sm font-semibold uppercase tracking-wider text-accent">Compensation</p><h1 className="text-3xl font-semibold">Payroll</h1><p className="mt-1 text-muted">Review compensation, deductions and payslips.</p></div><section className="grid gap-4 md:grid-cols-3"><StatCard label="Gross payroll" value={formatCurrency(query.data.gross)} icon={<CircleDollarSign />} /><StatCard label="Total deductions" value={formatCurrency(query.data.deductions)} icon={<ReceiptText />} accent="amber" /><StatCard label="Net payroll" value={formatCurrency(query.data.net)} icon={<Banknote />} accent="green" /></section><Card className="mt-6"><h2 className="mb-5 text-xl font-semibold">Employee payroll</h2><DataTable data={query.data.records} columns={columns} getRowKey={(r) => r.id} /></Card></div>
}

export function PayslipPage() {
  const { id = '' } = useParams(); const query = useQuery({ queryKey: ['payslip', id], queryFn: () => payrollApi.payslip(id), enabled: Boolean(id) })
  if (query.isLoading) return <Skeleton className="h-[700px]" />
  if (!query.data) return <EmptyState title="Payslip not found" />
  const slip = query.data
  return <div><div className="no-print mb-5 flex justify-end"><Button onClick={() => window.print()}><Printer size={17} />Print payslip</Button></div><Card className="print-surface mx-auto max-w-4xl p-8 sm:p-12"><div className="flex flex-wrap justify-between gap-6 border-b border-border pb-8"><div><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-lg bg-primary font-heading text-xl font-bold text-white">H</span><h1 className="text-2xl font-semibold">Hearth HR</h1></div><p className="mt-4 text-sm text-muted">Official salary statement</p></div><div className="text-right"><h2 className="text-2xl font-semibold">Payslip</h2><p className="font-mono text-sm text-muted">{slip.month}</p></div></div><div className="grid gap-6 border-b border-border py-8 sm:grid-cols-2"><div><p className="text-xs font-semibold uppercase text-muted">Employee</p><p className="mt-1 text-lg font-semibold">{slip.employeeName}</p><p className="font-mono text-sm text-muted">{slip.employeeId}</p></div><div className="sm:text-right"><p>{slip.jobTitle}</p><p className="text-muted">{slip.department}</p><Badge variant={slip.status}>{slip.status}</Badge></div></div><div className="grid gap-10 py-8 sm:grid-cols-2"><div><h3 className="mb-4 font-sans text-sm font-semibold uppercase text-muted">Earnings</h3>{slip.earnings.map((item) => <div key={item.label} className="flex justify-between border-b border-border py-3"><span>{item.label}</span><span className="font-mono">{formatCurrency(item.amount)}</span></div>)}</div><div><h3 className="mb-4 font-sans text-sm font-semibold uppercase text-muted">Deductions</h3>{slip.deductionItems.map((item) => <div key={item.label} className="flex justify-between border-b border-border py-3"><span>{item.label}</span><span className="font-mono">{formatCurrency(item.amount)}</span></div>)}</div></div><div className="rounded-lg bg-primary p-6 text-white"><div className="flex items-center justify-between"><span className="font-semibold">Net pay</span><strong className="font-mono text-2xl">{formatCurrency(slip.net)}</strong></div></div></Card></div>
}
