import type { SalaryComponentMetadata } from './types';

export const DEFAULT_SALARY_COMPONENTS: SalaryComponentMetadata[] = [
  // Earnings
  {
    code: 'BASIC',
    name: 'Basic Salary',
    type: 'Earning',
    calculationMethod: 'PercentageOfGross',
    formulaExpression: '0.50 * Gross',
    isTaxable: true,
    isStatutory: true,
    isEncashable: true,
    isPartCTC: true,
    isActive: true,
    effectiveFrom: '2026-04-01',
  },
  {
    code: 'HRA',
    name: 'House Rent Allowance',
    type: 'Earning',
    calculationMethod: 'PercentageOfBasic',
    formulaExpression: '0.50 * Basic',
    isTaxable: true, // Eligible for Section 10(13A) exemption
    isStatutory: false,
    isEncashable: false,
    isPartCTC: true,
    isActive: true,
    effectiveFrom: '2026-04-01',
  },
  {
    code: 'CONV',
    name: 'Conveyance Allowance',
    type: 'Earning',
    calculationMethod: 'Fixed',
    formulaExpression: '1600',
    isTaxable: true,
    isStatutory: false,
    isEncashable: false,
    isPartCTC: true,
    isActive: true,
    effectiveFrom: '2026-04-01',
  },
  {
    code: 'MED',
    name: 'Medical Allowance',
    type: 'Earning',
    calculationMethod: 'Fixed',
    formulaExpression: '1250',
    isTaxable: true,
    isStatutory: false,
    isEncashable: false,
    isPartCTC: true,
    isActive: true,
    effectiveFrom: '2026-04-01',
  },
  {
    code: 'LTA',
    name: 'Leave Travel Allowance',
    type: 'Earning',
    calculationMethod: 'Fixed',
    formulaExpression: '0',
    isTaxable: true,
    isStatutory: false,
    isEncashable: false,
    isPartCTC: true,
    isActive: true,
    effectiveFrom: '2026-04-01',
  },
  {
    code: 'SPECIAL',
    name: 'Special Allowance',
    type: 'Earning',
    calculationMethod: 'Formula',
    formulaExpression: 'Gross - (Basic + HRA + Conveyance + Medical)',
    isTaxable: true,
    isStatutory: false,
    isEncashable: false,
    isPartCTC: true,
    isActive: true,
    effectiveFrom: '2026-04-01',
  },
  {
    code: 'BONUS',
    name: 'Performance Bonus / Statutory Bonus',
    type: 'Earning',
    calculationMethod: 'Fixed',
    formulaExpression: '0',
    isTaxable: true,
    isStatutory: false,
    isEncashable: false,
    isPartCTC: false,
    isActive: true,
    effectiveFrom: '2026-04-01',
  },
  {
    code: 'INCENTIVE',
    name: 'Sales / Performance Incentive',
    type: 'Earning',
    calculationMethod: 'Fixed',
    formulaExpression: '0',
    isTaxable: true,
    isStatutory: false,
    isEncashable: false,
    isPartCTC: false,
    isActive: true,
    effectiveFrom: '2026-04-01',
  },
  {
    code: 'OVERTIME',
    name: 'Overtime Pay',
    type: 'Earning',
    calculationMethod: 'Formula',
    formulaExpression: '(Basic / (30 * 8)) * ApprovedHours * 1.5',
    isTaxable: true,
    isStatutory: false,
    isEncashable: false,
    isPartCTC: false,
    isActive: true,
    effectiveFrom: '2026-04-01',
  },
  {
    code: 'ARREARS',
    name: 'Salary Arrears',
    type: 'Earning',
    calculationMethod: 'Fixed',
    formulaExpression: '0',
    isTaxable: true,
    isStatutory: false,
    isEncashable: false,
    isPartCTC: false,
    isActive: true,
    effectiveFrom: '2026-04-01',
  },
  {
    code: 'REIMBURSEMENT',
    name: 'Expense Claim Reimbursement',
    type: 'Reimbursement',
    calculationMethod: 'Fixed',
    formulaExpression: 'ApprovedExpenseClaims',
    isTaxable: false, // Non-taxable expense reimbursements
    isStatutory: false,
    isEncashable: false,
    isPartCTC: false,
    isActive: true,
    effectiveFrom: '2026-04-01',
  },

  // Deductions & Statutory
  {
    code: 'PF_EMP',
    name: 'Provident Fund (Employee)',
    type: 'Statutory',
    calculationMethod: 'PercentageOfBasic',
    formulaExpression: 'min(1800, Basic * 0.12)',
    isTaxable: false,
    isStatutory: true,
    isEncashable: false,
    isPartCTC: false,
    isActive: true,
    effectiveFrom: '2026-04-01',
  },
  {
    code: 'PF_EMPR',
    name: 'Provident Fund (Employer)',
    type: 'Statutory',
    calculationMethod: 'PercentageOfBasic',
    formulaExpression: 'min(1800, Basic * 0.12)',
    isTaxable: false,
    isStatutory: true,
    isEncashable: false,
    isPartCTC: true,
    isActive: true,
    effectiveFrom: '2026-04-01',
  },
  {
    code: 'ESIC_EMP',
    name: 'ESIC (Employee)',
    type: 'Statutory',
    calculationMethod: 'PercentageOfGross',
    formulaExpression: 'Gross <= 21000 ? Gross * 0.0075 : 0',
    isTaxable: false,
    isStatutory: true,
    isEncashable: false,
    isPartCTC: false,
    isActive: true,
    effectiveFrom: '2026-04-01',
  },
  {
    code: 'ESIC_EMPR',
    name: 'ESIC (Employer)',
    type: 'Statutory',
    calculationMethod: 'PercentageOfGross',
    formulaExpression: 'Gross <= 21000 ? Gross * 0.0325 : 0',
    isTaxable: false,
    isStatutory: true,
    isEncashable: false,
    isPartCTC: true,
    isActive: true,
    effectiveFrom: '2026-04-01',
  },
  {
    code: 'PT',
    name: 'Professional Tax',
    type: 'Statutory',
    calculationMethod: 'Formula',
    formulaExpression: 'StateSpecificPTSlab(Gross, State, Month)',
    isTaxable: false,
    isStatutory: true,
    isEncashable: false,
    isPartCTC: false,
    isActive: true,
    effectiveFrom: '2026-04-01',
  },
  {
    code: 'TDS',
    name: 'Income Tax (TDS)',
    type: 'Deduction',
    calculationMethod: 'Formula',
    formulaExpression: 'IndianIncomeTaxEngine(TaxRegime, AnnualProjection, Declarations)',
    isTaxable: false,
    isStatutory: true,
    isEncashable: false,
    isPartCTC: false,
    isActive: true,
    effectiveFrom: '2026-04-01',
  },
  {
    code: 'LWF',
    name: 'Labour Welfare Fund',
    type: 'Statutory',
    calculationMethod: 'Formula',
    formulaExpression: 'StateSpecificLWF(State, Month)',
    isTaxable: false,
    isStatutory: true,
    isEncashable: false,
    isPartCTC: false,
    isActive: true,
    effectiveFrom: '2026-04-01',
  },
  {
    code: 'LOAN_EMI',
    name: 'Loan / Advance EMI Deduction',
    type: 'Deduction',
    calculationMethod: 'Fixed',
    formulaExpression: 'ActiveLoanEMI',
    isTaxable: false,
    isStatutory: false,
    isEncashable: false,
    isPartCTC: false,
    isActive: true,
    effectiveFrom: '2026-04-01',
  },
  {
    code: 'GRATUITY_PROV',
    name: 'Gratuity Provision (Employer)',
    type: 'Statutory',
    calculationMethod: 'Formula',
    formulaExpression: '(Basic * 15 / 26) / 12',
    isTaxable: false,
    isStatutory: true,
    isEncashable: false,
    isPartCTC: true,
    isActive: true,
    effectiveFrom: '2026-04-01',
  },
];
