import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CalendarPlus, Check, X } from 'lucide-react'
import { leaveApi } from '../../api/leave'
import { getErrorMessage } from '../../api/client'
import { Badge, Button, Card, DataTable, DatePicker, EmptyState, Modal, Select, Skeleton, type Column } from '../../components/ui'
import { useToast } from '../../components/ui/Toast'
import { useAuth } from '../../hooks/useAuth'
import type { LeaveInput, LeaveRequest, LeaveStatus } from '../../types'
import { formatDate } from '../../lib/utils'

export function LeavePage() {
  const [modal, setModal] = useState(false); const { can } = useAuth(); const { toast } = useToast(); const queryClient = useQueryClient(); const query = useQuery({ queryKey: ['leaves'], queryFn: leaveApi.list }); const { register, handleSubmit, reset, formState: { isSubmitting } } = useForm<LeaveInput>()
  const apply = useMutation({ mutationFn: leaveApi.apply, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['leaves'] }); toast('Leave request submitted', 'success'); setModal(false); reset() }, onError: (e) => toast(getErrorMessage(e), 'error') })
  const status = useMutation({ mutationFn: ({ id, value }: { id: string; value: Extract<LeaveStatus, 'APPROVED' | 'REJECTED'> }) => leaveApi.updateStatus(id, value), onMutate: async ({ id, value }) => { await queryClient.cancelQueries({ queryKey: ['leaves'] }); const previous = queryClient.getQueryData(['leaves']); queryClient.setQueryData(['leaves'], (old: typeof query.data) => old ? { ...old, requests: old.requests.map((r) => r.id === id ? { ...r, status: value } : r) } : old); return { previous } }, onError: (e, _, context) => { queryClient.setQueryData(['leaves'], context?.previous); toast(getErrorMessage(e), 'error') }, onSettled: () => queryClient.invalidateQueries({ queryKey: ['leaves'] }) })
  const columns: Column<LeaveRequest>[] = [{ key: 'employeeName', header: 'Employee' }, { key: 'type', header: 'Leave type' }, { key: 'dates', header: 'Dates', render: (r) => <span className="font-mono text-xs">{formatDate(r.startDate)} – {formatDate(r.endDate)}</span> }, { key: 'days', header: 'Days' }, { key: 'status', header: 'Status', render: (r) => <Badge variant={r.status}>{r.status}</Badge> }, { key: 'actions', header: '', render: (r) => can('SUPER_ADMIN', 'HR_MANAGER') && r.status === 'PENDING' ? <div className="flex gap-1"><Button variant="ghost" size="sm" aria-label="Approve" onClick={() => status.mutate({ id: r.id, value: 'APPROVED' })}><Check className="text-emerald-600" size={17} /></Button><Button variant="ghost" size="sm" aria-label="Reject" onClick={() => status.mutate({ id: r.id, value: 'REJECTED' })}><X className="text-red-600" size={17} /></Button></div> : null }]
  if (query.isLoading) return <Skeleton className="h-[600px]" />
  if (!query.data) return <EmptyState title="Unable to load leave data" action={<Button onClick={() => query.refetch()}>Retry</Button>} />
  return <div><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wider text-accent">Time away</p><h1 className="text-3xl font-semibold">Leave Management</h1><p className="mt-1 text-muted">Plan time off and manage employee requests.</p></div><Button onClick={() => setModal(true)}><CalendarPlus size={18} />Apply for leave</Button></div><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{query.data.balances.map((balance) => <Card key={balance.type}><div className="flex justify-between"><h3 className="font-sans text-sm font-semibold">{balance.type}</h3><span className="font-mono text-sm text-muted">{balance.total - balance.used}/{balance.total}</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-border"><div className="h-full rounded-full bg-accent" style={{ width: `${balance.total ? balance.used / balance.total * 100 : 0}%` }} /></div><p className="mt-2 text-xs text-muted">{balance.used} days used</p></Card>)}</section><Card className="mt-6"><h2 className="mb-5 text-xl font-semibold">Leave requests</h2><DataTable data={query.data.requests} columns={columns} getRowKey={(r) => r.id} /></Card><Modal open={modal} onClose={() => setModal(false)} title="Apply for leave"><form className="space-y-4" onSubmit={handleSubmit((v) => apply.mutate(v))}><Select label="Leave type" required {...register('type')}><option value="">Select leave type</option><option>Annual Leave</option><option>Sick Leave</option><option>Casual Leave</option><option>Unpaid Leave</option></Select><div className="grid grid-cols-2 gap-3"><DatePicker label="Start date" required {...register('startDate')} /><DatePicker label="End date" required {...register('endDate')} /></div><label className="block"><span className="mb-1.5 block text-sm font-medium">Reason</span><textarea className="min-h-28 w-full rounded-lg border border-border bg-surface p-3 focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20" required {...register('reason')} /></label><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setModal(false)}>Cancel</Button><Button type="submit" loading={isSubmitting || apply.isPending}>Submit request</Button></div></form></Modal></div>
}
