import { forwardRef, useEffect, useState, type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes } from 'react'
import { AlertCircle, ChevronLeft, ChevronRight, Inbox, Search, X } from 'lucide-react'
import { cn, initials } from '../../lib/utils'

export const Button = forwardRef<HTMLButtonElement, ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'ghost' | 'danger'; size?: 'sm' | 'md' | 'lg'; loading?: boolean }>(({ className, variant = 'primary', size = 'md', loading, children, disabled, ...props }, ref) => (
  <button ref={ref} disabled={disabled || loading} className={cn('inline-flex items-center justify-center gap-2 rounded-lg font-semibold transition focus-visible:ring-2 focus-visible:ring-accent disabled:cursor-not-allowed disabled:opacity-50', { primary: 'bg-primary text-white hover:bg-primary/90', secondary: 'border border-border bg-surface text-foreground hover:bg-background', ghost: 'text-muted hover:bg-primary/10 hover:text-primary', danger: 'bg-red-600 text-white hover:bg-red-700' }[variant], { sm: 'h-9 px-3 text-sm', md: 'h-11 px-4', lg: 'h-12 px-6' }[size], className)} {...props}>{loading && <span className="h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" />}{children}</button>
)); Button.displayName = 'Button'

export const Input = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement> & { label?: string; error?: string; icon?: ReactNode }>(({ className, label, error, icon, id, ...props }, ref) => {
  const inputId = id ?? props.name
  return <label className="block w-full" htmlFor={inputId}>{label && <span className="mb-1.5 block text-sm font-medium text-foreground">{label}</span>}<span className="relative block">{icon && <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted">{icon}</span>}<input ref={ref} id={inputId} aria-invalid={Boolean(error)} className={cn('h-11 w-full rounded-lg border border-border bg-surface px-3 text-foreground placeholder:text-muted/70 transition hover:border-primary/40 focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20', icon && 'pl-10', error && 'border-red-500', className)} {...props} /></span>{error && <span className="mt-1 flex items-center gap-1 text-sm text-red-600"><AlertCircle size={14} />{error}</span>}</label>
}); Input.displayName = 'Input'

export const Select = forwardRef<HTMLSelectElement, SelectHTMLAttributes<HTMLSelectElement> & { label?: string; error?: string }>(({ className, label, error, id, children, ...props }, ref) => <label className="block w-full" htmlFor={id ?? props.name}>{label && <span className="mb-1.5 block text-sm font-medium text-foreground">{label}</span>}<select ref={ref} id={id ?? props.name} className={cn('h-11 w-full rounded-lg border border-border bg-surface px-3 text-foreground focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20', className)} {...props}>{children}</select>{error && <span className="mt-1 block text-sm text-red-600">{error}</span>}</label>); Select.displayName = 'Select'
export const DatePicker = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement> & { label?: string; error?: string }>((props, ref) => <Input ref={ref} type="date" {...props} />); DatePicker.displayName = 'DatePicker'

export function Card({ children, className }: { children: ReactNode; className?: string }) { return <div className={cn('rounded-lg border border-border bg-surface p-5 shadow-soft', className)}>{children}</div> }
export function StatCard({ label, value, icon, trend, accent = 'plum' }: { label: string; value: string | number; icon: ReactNode; trend?: string; accent?: 'plum' | 'amber' | 'green' | 'red' }) { const styles = { plum: 'bg-primary/10 text-primary', amber: 'bg-accent/15 text-accent', green: 'bg-emerald-500/10 text-emerald-600', red: 'bg-red-500/10 text-red-600' }; return <Card><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-muted">{label}</p><p className="mt-2 font-heading text-3xl font-semibold text-foreground">{value}</p>{trend && <p className="mt-1 text-xs text-muted">{trend}</p>}</div><span className={cn('rounded-lg p-3', styles[accent])}>{icon}</span></div></Card> }

const badgeStyles: Record<string, string> = { ACTIVE: 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-400', PRESENT: 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-400', APPROVED: 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-400', PAID: 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-400', PENDING: 'bg-amber-500/15 text-amber-700 dark:text-amber-300', DRAFT: 'bg-amber-500/15 text-amber-700 dark:text-amber-300', LATE: 'bg-amber-500/15 text-amber-700 dark:text-amber-300', REJECTED: 'bg-red-500/10 text-red-700 dark:text-red-400', INACTIVE: 'bg-slate-500/10 text-slate-600 dark:text-slate-300', ABSENT: 'bg-red-500/10 text-red-700 dark:text-red-400', ON_LEAVE: 'bg-violet-500/10 text-violet-700 dark:text-violet-300', PROCESSED: 'bg-violet-500/10 text-violet-700 dark:text-violet-300' }
export function Badge({ children, variant }: { children: ReactNode; variant?: string }) { return <span className={cn('inline-flex rounded-full px-2.5 py-1 text-xs font-semibold', badgeStyles[variant ?? String(children)] ?? 'bg-primary/10 text-primary')}>{children}</span> }
export function Avatar({ name, src, size = 'md' }: { name: string; src?: string; size?: 'sm' | 'md' | 'lg' }) { return <span className={cn('inline-flex shrink-0 items-center justify-center overflow-hidden rounded-full bg-accent/20 font-semibold text-primary', { sm: 'h-8 w-8 text-xs', md: 'h-10 w-10 text-sm', lg: 'h-16 w-16 text-xl' }[size])}>{src ? <img src={src} alt={name} className="h-full w-full object-cover" /> : initials(name)}</span> }
export function Skeleton({ className }: { className?: string }) { return <div className={cn('animate-pulse rounded-lg bg-border/80', className)} /> }
export function EmptyState({ title = 'Nothing here yet', description, action }: { title?: string; description?: string; action?: ReactNode }) { return <div className="flex min-h-52 flex-col items-center justify-center p-8 text-center"><span className="rounded-full bg-primary/10 p-4 text-primary"><Inbox size={28} /></span><h3 className="mt-4 text-lg font-semibold">{title}</h3>{description && <p className="mt-1 max-w-md text-sm text-muted">{description}</p>}{action && <div className="mt-4">{action}</div>}</div> }

export function Modal({ open, onClose, title, children }: { open: boolean; onClose: () => void; title: string; children: ReactNode }) { useEffect(() => { const onKey = (e: KeyboardEvent) => e.key === 'Escape' && onClose(); if (open) document.addEventListener('keydown', onKey); return () => document.removeEventListener('keydown', onKey) }, [open, onClose]); if (!open) return null; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" role="dialog" aria-modal="true" aria-label={title} onMouseDown={(e) => e.target === e.currentTarget && onClose()}><div className="max-h-[90vh] w-full max-w-lg overflow-auto rounded-lg bg-surface p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><Button variant="ghost" size="sm" onClick={onClose} aria-label="Close modal"><X size={18} /></Button></div>{children}</div></div> }
export function Drawer({ open, onClose, title, children }: { open: boolean; onClose: () => void; title: string; children: ReactNode }) { if (!open) return null; return <div className="fixed inset-0 z-50 bg-black/50" role="dialog" aria-modal="true"><div className="absolute inset-y-0 right-0 w-full max-w-xl overflow-auto bg-surface p-6 shadow-2xl"><div className="mb-6 flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><Button variant="ghost" size="sm" onClick={onClose} aria-label="Close drawer"><X size={18} /></Button></div>{children}</div></div> }
export function Tabs({ tabs, active, onChange }: { tabs: string[]; active: string; onChange: (tab: string) => void }) { return <div className="flex gap-1 overflow-x-auto border-b border-border" role="tablist">{tabs.map((tab) => <button key={tab} role="tab" aria-selected={active === tab} onClick={() => onChange(tab)} className={cn('whitespace-nowrap border-b-2 px-4 py-3 text-sm font-semibold', active === tab ? 'border-accent text-primary' : 'border-transparent text-muted hover:text-foreground')}>{tab}</button>)}</div> }

export interface Column<T> { key: keyof T | string; header: string; render?: (row: T) => ReactNode; sortable?: boolean; className?: string }
export function DataTable<T extends object>({ data, columns, searchPlaceholder = 'Search...', searchable = true, pageSize = 8, getRowKey }: { data: T[]; columns: Column<T>[]; searchPlaceholder?: string; searchable?: boolean; pageSize?: number; getRowKey: (row: T) => string }) {
  const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [sort, setSort] = useState<{ key: string; asc: boolean } | null>(null)
  const filtered = data.filter((row) => JSON.stringify(row).toLowerCase().includes(search.toLowerCase())).sort((a, b) => { if (!sort) return 0; const av = String((a as Record<string, unknown>)[sort.key] ?? ''); const bv = String((b as Record<string, unknown>)[sort.key] ?? ''); return av.localeCompare(bv) * (sort.asc ? 1 : -1) })
  const pages = Math.max(1, Math.ceil(filtered.length / pageSize)); const rows = filtered.slice((Math.min(page, pages) - 1) * pageSize, Math.min(page, pages) * pageSize)
  return <div>{searchable && <div className="mb-4 max-w-sm"><Input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1) }} placeholder={searchPlaceholder} icon={<Search size={17} />} aria-label={searchPlaceholder} /></div>}<div className="overflow-x-auto rounded-lg border border-border"><table className="w-full border-collapse text-left"><thead className="bg-background"><tr>{columns.map((column) => <th key={String(column.key)} className={cn('whitespace-nowrap px-4 py-3 text-xs font-semibold uppercase tracking-wide text-muted', column.className)}><button disabled={!column.sortable} className="disabled:cursor-default" onClick={() => setSort((current) => ({ key: String(column.key), asc: current?.key === column.key ? !current.asc : true }))}>{column.header}</button></th>)}</tr></thead><tbody>{rows.map((row) => <tr key={getRowKey(row)} className="border-t border-border transition hover:bg-background/70">{columns.map((column) => <td key={String(column.key)} className={cn('whitespace-nowrap px-4 py-3 text-sm text-foreground', column.className)}>{column.render ? column.render(row) : String((row as Record<string, unknown>)[String(column.key)] ?? '')}</td>)}</tr>)}</tbody></table>{!rows.length && <EmptyState title="No matching records" description="Try changing your search or filters." />}</div>{pages > 1 && <div className="mt-4 flex items-center justify-between text-sm text-muted"><span>Page {Math.min(page, pages)} of {pages}</span><div className="flex gap-2"><Button variant="secondary" size="sm" disabled={page <= 1} onClick={() => setPage((p) => p - 1)} aria-label="Previous page"><ChevronLeft size={16} /></Button><Button variant="secondary" size="sm" disabled={page >= pages} onClick={() => setPage((p) => p + 1)} aria-label="Next page"><ChevronRight size={16} /></Button></div></div>}</div>
}
